'use strict';
const path=require('node:path'),crypto=require('node:crypto');
const stage=process.env.UNDAUNTED_TEST_STAGE;
if(!stage || !path.resolve(stage).startsWith(path.resolve(__dirname,'../../artifacts')+path.sep))throw new Error('Tests require a staged disposable backend.');
process.env.AUTH_MODE='APIKEY';process.env.REGISTRATION_MODE='OPEN';process.env.LOG_LEVEL='silent';
const keys=crypto.generateKeyPairSync('rsa',{modulusLength:2048,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}});
process.env.AUTH_SIGNING_PRIVKEY_B64=Buffer.from(keys.privateKey).toString('base64');
process.env.AUTH_SIGNING_PUBKEY_B64=Buffer.from(keys.publicKey).toString('base64');
const {CreateDisposableDatabase,SeedAccount}=require(path.join(stage,'test/harness.js'));
const context=CreateDisposableDatabase();
const seeded=SeedAccount(context,'LegacyVeteran');
const auth=require(path.join(stage,'dist/controllers/launcherAuth.js'));
const legacyKey='UUK_'+crypto.randomBytes(24).toString('hex');
context.Db.$client.prepare('INSERT INTO userapikeys (userId,keyHash) VALUES (?,?)').run(seeded.UserId,auth.TokenHash(legacyKey));
const {app}=require(path.join(stage,'dist/app.js'));
const server=app.listen(0,'127.0.0.1',()=>process.send({port:server.address().port,legacyAccount:{UUK:legacyKey,Username:'LegacyVeteran',userId:seeded.UserId}}));
process.on('message',message=>{if(message==='close')server.close(()=>{context.Cleanup();process.exit(0);});});
